### ISSUE TITLE
Wrong class names and missing style properties

### ISSUE THREAD

**Issue by honcho-man** [natheetarn/natheetarn.github.io#1]
You made some mistakes while using the media queries, i have made corrections to them. Check attached file or copy the code from this issue: 
`* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Raleway', sans-serif;
}

section {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    background-color: #252934;
}

section .content {
    position: relative;
    margin-top: 100px;
}

section .content h2 {
    color: #fff;
    font-size: 5vmax;
    font-weight: 800;
    text-align: center;
}

section .content p {
    max-width: 1000px;
}

#myName {
    background-image: linear-gradient(45deg, #1dcdfe, #34f5c5);
    background-repeat: repeat;
    background-size: 100%;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

section .menu {
    overflow: hidden;
    position: fixed;
    top: 0;
    width: 100%;
    height: 50px;
    z-index: 1;
    background-color: #1B242F;
}

section .menu a {
    float: left;
    display: block;
    text-align: center;
    padding: 14px;
    text-decoration: none;
    color: white;
    transition: all 0.5s ease;
}

section .menu a:hover {
    color: #1dcdfe;
}

.menu .icon {
    display: none;
}

@media screen and (max-width: 600px) {
    .menu a:not(:first-child) {
        display: none;
    }
    .menu a.icon {
        float: right;
        display: block;
    }
    .icon {
        position: fixed;
        top: 0;
        right: 0;
        padding: 15px !important;
    }
}

@media screen and (max-width: 600px) {
    .menuresponsive {
        position: fixed;
        right: 0;
        top: 0;
        overflow: hidden;
        width: 100%;
        height: 50px;
        z-index: 1;
        background-color: #1B242F;
        padding: 15px;
    }
    .menuresponsive a {
        padding: 7px;
        transition: all 0.5s ease;
        text-decoration: none;
        color: white;
    }
}

section .content .button {
    color: white;
    background-color: transparent;
    display: block;
    border-style: solid;
    border-color: white;
    text-align: center;
    max-width: 200px;
    font-size: 5vh;
    padding: 1vh;
    margin: auto;
    margin-top: 70px;
    position: relative;
    transition: all 0.5s ease-in-out;
}

section .content .button a {
    color: white;
    text-decoration: none;
}

section .content .button:hover {
    background-color: red;
    border-color: red;
}`
[style.zip](https://github.com/natheetarn/natheetarn.github.io/files/5119967/style.zip)

**Comment by natheetarn** [comment]
Thanks so much for your time XX
